In [0]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
df = pd.read_csv("/content/drive/My Drive/DataSetk-means.csv")

## Converting Categorical Data to Numeric

In [0]:
df['weather_description'] = df['weather_description'].astype('category')
df['weather_main'] = dfrr['weather_main'].astype('category')
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)

In [84]:
ground_truth = df['weather_main'].values
print(ground_truth)

[1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0
 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 6 1 1 1 1 1 1 1 1 1 1 1 1 0 6 2 6 2 6 2 0
 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 6 2
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1
 1 1 1 1 1 1 1 1 1 5 2 5 4 2 5 2 5 5 6 2 6 5 2 5 6 2 5 6 5 6 5 5 5 5 5 5 5
 3 5 3 3 3 5 3 5 3 5 3 5 5 5 5 5 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1
 1 1 1 1 1 0 1 1 1 1 1 6 1 1 1 1 1 1 1 1 1 1 1 1 1 6 6 1 1 0 0 0 0 0 0 1 1
 1 1 1 1 1 1 5 5 1 5 1 1 1 6 1 1 6 1 1 1 1 1 1 2 6 2 1 1 1 5 2 5 5 2 5 6 2
 5 6 2 5 6 5 6 2 5 6 6 5 5 1 1 1 5 5 2 6 6 1 1 1 5 2 2 5 6 2 6 6 2 6 2 2 5
 5 2 6 6 5 2 6 5 2 6 5 2 6 5 2 6 2 5 2 6 2 5 6 6 5 2 6 5 6 6 6 1 1 1 1 1 1
 1 1 5 3 5 3 5 1 1 1 1 1 1 1 1 5 5 5]

## One-Hot Encoding Weather Description

In [0]:
nb_classes = len(df['weather_description'].unique())

def indices_to_one_hot(data, nb_classes):
    """Convert an iterable of indices to one-hot encoded labels."""
    targets = np.array(data).reshape(-1)
    return np.eye(nb_classes)[targets]
  
arr = indices_to_one_hot(df['weather_description'], nb_classes)

In [0]:
encoded_wd = pd.DataFrame(arr)
dfx = df.join(encoded_wd)

In [0]:
df_final = dfx.drop(['weather_description', 'weather_main'], axis = 1)

In [100]:
df_final

       temp  rain_1h  snow_1h  clouds_all  ...   10   11   12   13
0    288.28        0        0          40  ...  0.0  0.0  1.0  0.0
1    289.36        0        0          75  ...  0.0  0.0  0.0  0.0
2    289.58        0        0          90  ...  1.0  0.0  0.0  0.0
3    290.13        0        0          90  ...  1.0  0.0  0.0  0.0
4    291.14        0        0          75  ...  0.0  0.0  0.0  0.0
5    291.72        0        0           1  ...  0.0  0.0  0.0  1.0
6    293.17        0        0           1  ...  0.0  0.0  0.0  1.0
7    293.86        0        0           1  ...  0.0  0.0  0.0  1.0
8    294.14        0        0          20  ...  0.0  0.0  0.0  0.0
9    293.10        0        0          20  ...  0.0  0.0  0.0  0.0
10   290.97        0        0          20  ...  0.0  0.0  0.0  0.0
11   289.38        0        0           1  ...  0.0  0.0  0.0  1.0
12   288.61        0        0           1  ...  0.0  0.0  0.0  1.0
13   287.16        0        0           1  ...  0.0  0.0  0.0  1.0
14   285.45        0        0           1  ...  0.0  0.0  0.0  1.0
15   284.63        0        0           1  ...  0.0  0.0  0.0  1.0
16   283.47        0        0           1  ...  0.0  0.0  0.0  1.0
17   281.18        0        0           1  ...  0.0  0.0  0.0  1.0
18   281.09        0        0           1  ...  0.0  0.0  0.0  1.0
19   279.53        0        0           1  ...  0.0  0.0  0.0  1.0
20   278.62        0        0           1  ...  0.0  0.0  0.0  1.0
21   278.23        0        0           1  ...  0.0  0.0  0.0  1.0
22   278.12        0        0           1  ...  0.0  0.0  0.0  1.0
23   282.48        0        0           1  ...  0.0  0.0  0.0  1.0
24   291.97        0        0           1  ...  0.0  0.0  0.0  1.0
25   293.23        0        0           1  ...  0.0  0.0  0.0  1.0
26   294.31        0        0           1  ...  0.0  0.0  0.0  1.0
27   295.17        0        0           1  ...  0.0  0.0  0.0  1.0
28   295.13        0        0           1  ...  0.0  0.0  0.0  1.0
29   293.66        0        0          20  ...  0.0  0.0  0.0  0.0
..      ...      ...      ...         ...  ...  ...  ...  ...  ...
469  282.35        0        0         100  ...  0.0  0.0  0.0  0.0
470  282.71        0        0         100  ...  0.0  0.0  0.0  0.0
471  282.71        0        0         100  ...  0.0  0.0  0.0  0.0
472  282.71        0        0         100  ...  0.0  0.0  0.0  0.0
473  282.71        0        0         100  ...  0.0  0.0  0.0  0.0
474  283.31        0        0          48  ...  0.0  0.0  0.0  0.0
475  283.79        0        0          90  ...  1.0  0.0  0.0  0.0
476  284.20        0        0          75  ...  0.0  0.0  0.0  0.0
477  284.32        0        0          90  ...  1.0  0.0  0.0  0.0
478  284.13        0        0          75  ...  0.0  0.0  0.0  0.0
479  283.14        0        0          40  ...  0.0  0.0  1.0  0.0
480  281.40        0        0          40  ...  0.0  0.0  1.0  0.0
481  280.47        0        0          20  ...  0.0  0.0  0.0  0.0
482  279.52        0        0          20  ...  0.0  0.0  0.0  0.0
483  278.85        0        0          48  ...  0.0  0.0  0.0  0.0
484  278.12        0        0          48  ...  0.0  0.0  0.0  0.0
485  277.94        0        0          48  ...  0.0  0.0  0.0  0.0
486  275.93        0        0          60  ...  0.0  0.0  0.0  0.0
487  275.93        0        0          60  ...  0.0  0.0  0.0  0.0
488  284.09        0        0          75  ...  0.0  0.0  0.0  0.0
489  282.60        0        0          75  ...  0.0  0.0  0.0  0.0
490  281.72        0        0          90  ...  1.0  0.0  0.0  0.0
491  281.26        0        0          90  ...  1.0  0.0  0.0  0.0
492  281.29        0        0          75  ...  0.0  0.0  0.0  0.0
493  281.01        0        0          75  ...  0.0  0.0  0.0  0.0
494  280.57        0        0          40  ...  0.0  0.0  1.0  0.0
495  280.54        0        0          75  ...  0.0  0.0  0.0  0.0
496  279.37        0        0           8  ...  0.0  0.0  0.0  0.0
497  279.18        0        0           8  ...  0.0  0.0  0.0  0.0
498  279.05        0        0           8  ...  0.0  0.0  0.0  0.0

[499 rows x 19 columns]

## Normalising the Dataframe

In [0]:
x = df_final.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

df_norm = pd.DataFrame(x_scaled, columns=df_final.columns)

In [102]:
df_norm

         temp  rain_1h  snow_1h  clouds_all  ...   10   11   12   13
0    0.661996      0.0      0.0        0.40  ...  0.0  0.0  1.0  0.0
1    0.698906      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
2    0.706425      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
3    0.725222      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
4    0.759740      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
5    0.779563      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
6    0.829118      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
7    0.852700      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
8    0.862269      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
9    0.826726      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
10   0.753930      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
11   0.699590      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
12   0.673274      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
13   0.623718      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
14   0.565277      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
15   0.537252      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
16   0.497608      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
17   0.419344      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
18   0.416268      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
19   0.362953      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
20   0.331852      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
21   0.318524      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
22   0.314764      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
23   0.463773      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
24   0.788107      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
25   0.831169      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
26   0.868079      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
27   0.897471      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
28   0.896104      0.0      0.0        0.01  ...  0.0  0.0  0.0  1.0
29   0.845865      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
..        ...      ...      ...         ...  ...  ...  ...  ...  ...
469  0.459330      0.0      0.0        1.00  ...  0.0  0.0  0.0  0.0
470  0.471634      0.0      0.0        1.00  ...  0.0  0.0  0.0  0.0
471  0.471634      0.0      0.0        1.00  ...  0.0  0.0  0.0  0.0
472  0.471634      0.0      0.0        1.00  ...  0.0  0.0  0.0  0.0
473  0.471634      0.0      0.0        1.00  ...  0.0  0.0  0.0  0.0
474  0.492139      0.0      0.0        0.48  ...  0.0  0.0  0.0  0.0
475  0.508544      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
476  0.522556      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
477  0.526658      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
478  0.520164      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
479  0.486329      0.0      0.0        0.40  ...  0.0  0.0  1.0  0.0
480  0.426863      0.0      0.0        0.40  ...  0.0  0.0  1.0  0.0
481  0.395079      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
482  0.362611      0.0      0.0        0.20  ...  0.0  0.0  0.0  0.0
483  0.339713      0.0      0.0        0.48  ...  0.0  0.0  0.0  0.0
484  0.314764      0.0      0.0        0.48  ...  0.0  0.0  0.0  0.0
485  0.308612      0.0      0.0        0.48  ...  0.0  0.0  0.0  0.0
486  0.239918      0.0      0.0        0.60  ...  0.0  0.0  0.0  0.0
487  0.239918      0.0      0.0        0.60  ...  0.0  0.0  0.0  0.0
488  0.518797      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
489  0.467874      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
490  0.437799      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
491  0.422078      0.0      0.0        0.90  ...  1.0  0.0  0.0  0.0
492  0.423103      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
493  0.413534      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
494  0.398496      0.0      0.0        0.40  ...  0.0  0.0  1.0  0.0
495  0.397471      0.0      0.0        0.75  ...  0.0  0.0  0.0  0.0
496  0.357485      0.0      0.0        0.08  ...  0.0  0.0  0.0  0.0
497  0.350991      0.0      0.0        0.08  ...  0.0  0.0  0.0  0.0
498  0.346548      0.0      0.0        0.08  ...  0.0  0.0  0.0  0.0

[499 rows x 19 columns]

# K-Means Clustering

In [0]:
from random import sample
from math import sqrt
from numpy import mean
import copy


def accuracy(cluster_labels, class_labels):
    county = [0,0]
    countn = [0,0]
    tp = [0, 0]
    tn = [0, 0]
    fp = [0, 0]
    fn = [0, 0]
    
    for i in range(len(df)):
        # Yes = 1, No = 0
        if cluster_labels[i] == 1 and class_labels[i] == 'Yes':
            tp[0] = tp[0] + 1
        if cluster_labels[i] == 0 and class_labels[i] == 'No':
            tn[0] = tn[0] + 1
        if cluster_labels[i] == 1 and class_labels[i] == 'No':
            fp[0] = fp[0] + 1
        if cluster_labels[i] == 0 and class_labels[i] == 'Yes':
            fn[0] = fn[0] + 1
    
    for i in range(len(df)):
        # Yes = 0, No = 1
        if cluster_labels[i] == 0 and class_labels[i] == 'Yes':
            tp[1] = tp[1] + 1
        if cluster_labels[i] == 1 and class_labels[i] == 'No':
            tn[1] = tn[1] + 1
        if cluster_labels[i] == 0 and class_labels[i] == 'No':
            fp[1] = fp[1] + 1
        if cluster_labels[i] == 1 and class_labels[i] == 'Yes':
            fn[1] = fn[1] + 1
    
    a0 = float((tp[0] + tn[0]))/(tp[0] + tn[0] + fn[0] + fp[0])
    a1 = float((tp[1] + tn[1]))/(tp[1] + tn[1] + fn[1] + fp[1])
    p0 = float(tp[0])/(tp[0] + fp[0])
    p1 = float(tp[1])/(tp[1] + fp[1])
    r0 = float(tp[0])/(tp[0] + fn[0])
    r1 = float(tp[1])/(tp[1] + fn[1])
    
    accuracy = [a0*100,a1*100]
    precision = [p0*100,p1*100]
    recall = [r0*100,r1*100]
    
    return accuracy, precision, recall


def initializeCenters(df, k):
    random_indices = sample(range(len(df)), k)
    centers = [list(df.iloc[idx]) for idx in random_indices]
    print("Random Indices : " + str(random_indices))
    return centers


def computeCenter(df, k, cluster_labels):
    cluster_centers = list()
    data_points = list()
    for i in range(k):
        for idx, val in enumerate(cluster_labels):
            if val == i:
                data_points.append(list(df.iloc[idx]))
        cluster_centers.append(map(mean, zip(*data_points)))
    return cluster_centers


def euclidean_distance(x, y):
    summ = 0
    for i in range(len(x)):
        term = (x[i] - y[i])**2
        summ += term
    return sqrt(summ)


def assignCluster(df, k, cluster_centers):
    cluster_assigned = list()
    for i in range(len(df)):
        distances = [euclidean_distance(list(df.iloc[i]), center) for center in cluster_centers]
        min_dist, idx = min((val, idx) for (idx, val) in enumerate(distances))
        cluster_assigned.append(idx)
    return cluster_assigned


def kmeans(df, k, class_labels):
    cluster_centers = initializeCenters(df, k)
    curr = 1
    
    while curr <= MAX_ITER:
        cluster_labels = assignCluster(df, k, cluster_centers)
    #     print (cluster_labels)
        prev_centers = copy.deepcopy(cluster_centers)
    #     print("Previous Cluster Centers: \n")
        cluster_centers = computeCenter(df, k, cluster_labels)
        curr += 1
#         print("Cluster 0: " + str(euclidean_distance(prev_centers[0], cluster_centers[0])))
#         print("Cluster 1: " + str(euclidean_distance(prev_centers[1], cluster_centers[1])))
    
    return cluster_labels, cluster_centers

### k=3

In [114]:
k = 3
MAX_ITER = 100

class_labels = list(df['weather_main'])

labels_k3, centers_k3 = kmeans(df_norm, k, class_labels)

Random Indices : [19, 20, 80]

In [116]:
def indices(mylist, value):
    return [i for i,x in enumerate(mylist) if x==value]

for i in range(k):
  print "Cluster", i
  print indices(labels_k3,i)

Cluster 0
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 32, 33, 34, 35, 36, 37, 38, 39, 40, 61, 86, 87, 88, 128, 129, 130, 131, 146, 147, 148, 149, 150, 151, 152, 192, 193, 194, 195, 196, 197, 235, 236, 237, 238, 240, 241, 242, 256, 326, 327, 328, 329, 330]
Cluster 1
[5, 6, 7, 8, 9, 10, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 85, 90, 91, 125, 126, 127, 132, 133, 134, 135, 136, 137, 138, 141, 142, 145, 153, 177, 185, 190, 191, 201, 202, 203, 204, 205, 206, 207, 234, 239, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 315, 316, 317, 318, 319, 323, 325, 331, 332, 333, 334, 335, 336, 338, 362, 363, 364, 365, 366, 367, 372, 373, 374, 481, 482]
Cluster 2
[0, 1, 2, 3, 4, 53, 54, 55, 56, 57, 58, 59, 60, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 89, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 139, 140, 143, 144, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 178, 179, 180, 181, 182, 183, 184, 186, 187, 188, 189, 198, 199, 200, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 243, 244, 245, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 320, 321, 322, 324, 337, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 368, 369, 370, 371, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498]

### k=5

In [119]:
k=5

labels_k5, centers_k5 = kmeans(df_norm, k, class_labels)

Random Indices : [374, 113, 143, 497, 272]

In [120]:
for i in range(k):
  print "Cluster", i
  print indices(labels_k5,i)

Cluster 0
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 61, 85, 86, 87, 88, 90, 91, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 141, 142, 145, 146, 147, 148, 149, 150, 151, 152, 153, 185, 197, 201, 202, 203, 204, 205, 206, 207, 234, 235, 236, 237, 238, 239, 240, 241, 242, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 315, 316, 317, 318, 319, 323, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 338, 362, 363, 364, 365, 366, 367, 372, 373, 374, 481, 482]
Cluster 1
[2, 3, 63, 64, 65, 68, 69, 71, 72, 73, 74, 75, 76, 77, 81, 82, 83, 96, 97, 98, 99, 100, 101, 102, 105, 106, 108, 109, 113, 114, 115, 116, 117, 118, 119, 120, 121, 123, 157, 158, 159, 160, 163, 165, 166, 167, 169, 170, 171, 172, 173, 174, 176, 188, 189, 210, 211, 212, 213, 214, 215, 216, 217, 218, 224, 225, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 312, 322, 343, 345, 346, 347, 348, 351, 352, 354, 355, 378, 381, 382, 384, 385, 387, 388, 389, 390, 391, 392, 396, 397, 398, 420, 421, 422, 428, 430, 475, 477, 490, 491]
Cluster 2
[]
Cluster 3
[177, 184, 190, 191, 192, 193, 194, 195, 196, 313]
Cluster 4
[0, 1, 4, 53, 54, 55, 56, 57, 58, 59, 60, 62, 66, 67, 70, 78, 79, 80, 84, 89, 92, 93, 94, 95, 103, 104, 107, 110, 111, 112, 122, 124, 139, 140, 143, 144, 154, 155, 156, 161, 162, 164, 168, 175, 178, 179, 180, 181, 182, 183, 186, 187, 198, 199, 200, 208, 209, 219, 220, 221, 222, 223, 226, 227, 228, 229, 230, 231, 232, 233, 243, 244, 245, 257, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 314, 320, 321, 324, 337, 339, 340, 341, 342, 344, 349, 350, 353, 356, 357, 358, 359, 360, 361, 368, 369, 370, 371, 375, 376, 377, 379, 380, 383, 386, 393, 394, 395, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 423, 424, 425, 426, 427, 429, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 476, 478, 479, 480, 483, 484, 485, 486, 487, 488, 489, 492, 493, 494, 495, 496, 497, 498]

### k=7

In [125]:
k=7
MAX_ITER = 1000

labels_k7, centers_k7 = kmeans(df_norm, k, class_labels)

Random Indices : [468, 129, 152, 275, 190, 159, 415]

In [126]:
for i in range(k):
  print "Cluster", i
  print indices(labels_k7,i)

Cluster 0
[268, 270, 273, 275, 276, 280, 282, 285, 287, 289, 290, 291, 292, 293, 294, 295, 297, 301, 303, 305, 307, 308, 309, 310, 311, 376, 377, 379, 399, 401, 402, 404, 407, 410, 412, 415, 418, 419, 423, 424, 431, 434, 443, 444, 448, 451, 454, 457, 461, 465, 468, 471, 483, 485, 487, 496, 497, 498]
Cluster 1
[]
Cluster 2
[164, 178, 179, 180, 181, 182, 183, 219, 220, 221, 277, 279, 281, 283, 284, 286, 288, 344, 359, 383, 386, 393, 394, 395, 400, 403, 405, 406, 408, 409, 411, 414, 416, 417, 425, 427, 432, 433, 435, 436, 437, 439, 440, 441, 442, 445, 446, 447, 449, 450, 452, 453, 455, 456, 458, 459, 460, 462, 463, 464, 467, 469, 472, 474]
Cluster 3
[]
Cluster 4
[5, 6, 7, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 61, 86, 87, 88, 128, 129, 130, 131, 138, 141, 142, 146, 147, 148, 149, 150, 151, 152, 177, 184, 185, 190, 191, 192, 193, 194, 195, 196, 197, 201, 202, 203, 205, 206, 207, 235, 236, 237, 238, 240, 241, 242, 247, 248, 249, 250, 251, 252, 253, 254, 256, 313, 315, 316, 326, 327, 328, 329, 330, 331, 338, 362, 363, 364, 365, 366, 367]
Cluster 5
[0, 8, 9, 10, 29, 30, 31, 51, 52, 53, 54, 55, 60, 79, 80, 85, 89, 90, 91, 92, 125, 126, 127, 132, 133, 134, 135, 136, 137, 139, 140, 143, 144, 145, 153, 154, 155, 200, 204, 228, 229, 233, 234, 239, 244, 245, 246, 255, 314, 317, 318, 319, 323, 325, 332, 333, 334, 335, 336, 337, 368, 369, 370, 371, 372, 373, 374, 375, 479, 480, 481, 482, 494]
Cluster 6
[1, 2, 3, 4, 56, 57, 58, 59, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 81, 82, 83, 84, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 156, 157, 158, 159, 160, 161, 162, 163, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 186, 187, 188, 189, 198, 199, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 222, 223, 224, 225, 226, 227, 230, 231, 232, 243, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 269, 271, 272, 274, 278, 296, 298, 299, 300, 302, 304, 306, 312, 320, 321, 322, 324, 339, 340, 341, 342, 343, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 360, 361, 378, 380, 381, 382, 384, 385, 387, 388, 389, 390, 391, 392, 396, 397, 398, 413, 420, 421, 422, 426, 428, 429, 430, 438, 466, 470, 473, 475, 476, 477, 478, 484, 486, 488, 489, 490, 491, 492, 493, 495]

# Rand_Index Calculation

In [0]:
from scipy.special import comb
from itertools import combinations
import numpy as np

def check_clusterings(labels_true, labels_pred):
    """Check that the two clusterings matching 1D integer arrays."""
    labels_true = np.asarray(labels_true)
    labels_pred = np.asarray(labels_pred)    
    # input checks
    if labels_true.ndim != 1:
        raise ValueError(
            "labels_true must be 1D: shape is %r" % (labels_true.shape,))
    if labels_pred.ndim != 1:
        raise ValueError(
            "labels_pred must be 1D: shape is %r" % (labels_pred.shape,))
    if labels_true.shape != labels_pred.shape:
        raise ValueError(
            "labels_true and labels_pred must have same size, got %d and %d"
            % (labels_true.shape[0], labels_pred.shape[0]))
    return labels_true, labels_pred

def rand_score (labels_true, labels_pred):
  """given the true and predicted labels, it will return the Rand Index."""
  check_clusterings(labels_true, labels_pred)
  my_pair = list(combinations(range(len(labels_true)), 2)) #create list of all combinations with the length of labels.
  def is_equal(x):
      return (x[0]==x[1])
  my_a = 0
  my_b = 0
  for i in range(len(my_pair)):
          if(is_equal((labels_true[my_pair[i][0]],labels_true[my_pair[i][1]])) == is_equal((labels_pred[my_pair[i][0]],labels_pred[my_pair[i][1]])) 
             and is_equal((labels_pred[my_pair[i][0]],labels_pred[my_pair[i][1]])) == True):
              my_a += 1
          if(is_equal((labels_true[my_pair[i][0]],labels_true[my_pair[i][1]])) == is_equal((labels_pred[my_pair[i][0]],labels_pred[my_pair[i][1]])) 
             and is_equal((labels_pred[my_pair[i][0]],labels_pred[my_pair[i][1]])) == False):
              my_b += 1
  my_denom = comb(len(labels_true),2)
  ri = (my_a + my_b) / my_denom
  return ri

In [128]:
print "For k=3: Rand Index:", rand_score (ground_truth, labels_k3)
print "For k=5: Rand Index:", rand_score (ground_truth, labels_k5)
print "For k=7: Rand Index:", rand_score (ground_truth, labels_k7)

For k=3: Rand Index: 0.5877055315450177
For k=5: Rand Index: 0.634916419183749
For k=7: Rand Index: 0.8545766231257697